[build]
  # base = ""
  publish = "book/"
  # Default build command.
  # command = "echo 'default context'"

# [context.production]
#   publish = "book/"

# [context.deploy-preview]
#   publish = "book/"

# Example redirects
[[redirects]]
  from = "/test-redirect"
  to = "/dummy-404"

# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
